name: Deploy Web Dashboard

on:
  push:
    branches: ["main"]
    paths:
      - "web/**" # Apenas rodar o deploy se a pasta web tiver sido modificada
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web

    steps:
      - name: Fazer checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          # O cache requer o package-lock.json, que não está presente inicialmente
          # cache: "npm"
          # cache-dependency-path: web/package-lock.json

      # Se o package-lock.json ainda não existir (primeira execução), podemos precisar gerá-lo ou usar o install
      - name: Instalar Dependências
        run: npm install

      - name: Construir Aplicação
        run: npm run build

      - name: Fazer Deploy no GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: web/dist # A pasta de saída do build
          branch: gh-pages # A branch para a qual a action deve fazer deploy.
